### ISSUE TITLE
Some latex typos in Math dataset

### ISSUE THREAD

**Issue by jinze1994** [hendrycks/math#10]
I try to show the dataset in a pdf file, and most of the latex files are good to transfer. But there are still some latex typos in:

1. `test/intermediate_algebra/44.json`

A URL appears to be mistakenly included in a JSON file, like

```
    "solution": "... the diagram,\n\nhttp://aops-classroom.s3.amazonaws.com/Algebra3/Algebra3_Putnam1958_Morning1.png\n\n ..."
```

Is it possible to correct this into a parsable form?

2. `test/prealgebra/1117.json`

```
"solution": "A $60 coat with a 20$\\%$ discount
```

3. `test/number_theory/407.json`
something like:
```
6 3 _ _ _ _
```

4. `./test/prealgebra/1645.json`
```
times $24.50 per square yard, or $\boxed{735}$ dollars.
```

**Comment by hendrycks** [comment]
I've uploaded a modified TAR file that hopefully addresses these issues.
